# NetworkPolicies to allow Prometheus to scrape Triton metrics
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-triton-prometheus
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: triton-amd
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: 8002
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-triton-embeddings-prometheus
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: triton-embeddings
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: 8002
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-triton-gpu-prometheus
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: triton-gpu
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: 8002
      protocol: TCP
