apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookmarked.fullname" . }}-api
  labels:
    app: {{ include "bookmarked.name" . }}-api
    chart: {{ include "bookmarked.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.api.type "NodePort") .Values.service.api.nodePort }}
      nodePort: {{ .Values.service.api.nodePort }}
      {{- end }}
  selector:
    app: {{ include "bookmarked.name" . }}-api
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookmarked.fullname" . }}-client
  labels:
    app: {{ include "bookmarked.name" . }}-client
    chart: {{ include "bookmarked.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.client.type }}
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.client.type "NodePort") .Values.service.client.nodePort }}
      nodePort: {{ .Values.service.client.nodePort }}
      {{- end }}
  selector:
    app: {{ include "bookmarked.name" . }}-client
    release: {{ .Release.Name }}
