apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-api-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-devops-api-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: podrick.el-jefe.me
    http:
      paths:
      - path: /devops-api
        pathType: Prefix
        backend:
          service:
            name: devops-portfolio-api
            port:
              number: 5001
