apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: podrick.el-jefe.me
    http:
      paths:
      - path: /devops-api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: devops-portfolio-api
            port:
              number: 5001
