apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - podrick.el-jefe.me
    secretName: podrick-tls
  rules:
  - host: podrick.el-jefe.me
    http:
      paths:
      - path: /devops-api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: devops-portfolio-api
            port:
              number: 5001
