apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-api-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-devops-api-stripprefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.priority: "200"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - podrick.el-jefe.me
    secretName: podrick-tls
  rules:
  - host: podrick.el-jefe.me
    http:
      paths:
      - path: /devops-api
        pathType: Prefix
        backend:
          service:
            name: devops-portfolio-api
            port:
              number: 5001
