apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-gateway-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: HUGGINGFACE_API_KEY
    secretKey: HUGGINGFACE_API_KEY
  - remoteRef:
      key: ANTHROPIC_API_KEY
    secretKey: ANTHROPIC_API_KEY
  - remoteRef:
      key: GROQ_API_KEY
    secretKey: GROQ_API_KEY
  - remoteRef:
      key: RUNPOD_API_KEY
    secretKey: RUNPOD_API_KEY
  - remoteRef:
      key: RUNPOD_ENDPOINT_ID
    secretKey: RUNPOD_ENDPOINT_ID
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ai-gateway-credentials
