apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: CLOUDFLARE_API_TOKEN
    secretKey: api-token
  - remoteRef:
      key: CLOUDFLARE_ZONE_ID
    secretKey: zone-id
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-secrets
