apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: code-talk-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: CODE_TALK_DATABASE_URL
    secretKey: DATABASE_URL
  - remoteRef:
      key: CODE_TALK_JWT_SECRET
    secretKey: JWT_SECRET
  - remoteRef:
      key: CODE_TALK_JWT_REFRESH_SECRET
    secretKey: JWT_REFRESH_SECRET
  - remoteRef:
      key: CODE_TALK_REDIS_URL
    secretKey: REDIS_URL
  - remoteRef:
      key: CODE_TALK_UPSTASH_REDIS_REST_URL
    secretKey: UPSTASH_REDIS_REST_URL
  - remoteRef:
      key: CODE_TALK_UPSTASH_REDIS_REST_TOKEN
    secretKey: UPSTASH_REDIS_REST_TOKEN
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: code-talk-secret

