apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tenantflow-neon-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: TENANTFLOW_NEON_API_KEY
    secretKey: NEON_API_KEY
  - remoteRef:
      key: TENANTFLOW_NEON_PROJECT_ID
    secretKey: NEON_PROJECT_ID
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: tenantflow-neon-credentials
