apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vertex-platform-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: VERTEX_JWT_SECRET
    secretKey: jwt-secret
  - remoteRef:
      key: KAFKA_BROKERS
    secretKey: kafka-brokers
  - remoteRef:
      key: KAFKA_USERNAME
    secretKey: kafka-username
  - remoteRef:
      key: KAFKA_PASSWORD
    secretKey: kafka-password
  - remoteRef:
      key: INFLUXDB_TOKEN
    secretKey: influxdb-token
  - remoteRef:
      key: NEON_DATABASE_URL
    secretKey: auth-database-url
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: vertex-platform-secret

