{{- if and .Values.ingress.enabled .Values.ingress.wwwRedirect }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-www-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    traefik.ingress.kubernetes.io/router.middlewares: default-{{ .Release.Name }}-www-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - www.{{ .Values.ingress.host }}
    secretName: {{ .Release.Name }}-www-tls
  rules:
  - host: www.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-client
            port:
              number: {{ .Values.service.client.port }}
{{- end }}
