apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intervalai.fullname" . }}-config
  labels:
    app: {{ include "intervalai.name" . }}
    chart: {{ include "intervalai.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
