apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firebook.fullname" . }}-client
  labels:
    app: {{ include "firebook.name" . }}-client
    {{- include "firebook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "firebook.name" . }}-client
      {{- include "firebook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "firebook.name" . }}-client
        {{- include "firebook.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "firebook.serviceAccountName" . }}
      containers:
      - name: client
        image: "{{ .Values.image.client.repository }}:{{ .Values.image.client.tag }}"
        imagePullPolicy: {{ .Values.image.client.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.client.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.env.client }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources.client | nindent 12 }}
